version: '3'

services:

  web-server:
    build:
      context: ./web
    ports:
      - 80:6000 # host : container
    env_file:
      ./credentials.env
    volumes:
      - ./web/src:/app
    container_name: agile-web

  db-server:
    image: mysql:latest
    restart: always
    env_file:
      ./credentials.env
    ports:
      - 3306:3306 # host : container
    volumes:
      - ./db:/var/lib/mysql # persistent DB when container is stopped
    container_name: agile-db

  mysql-db:
     image: mysql:latest
     restart: always
     env_file:
       ./credentials.env
     ports:
       - 3305:3305
     command: --init-file /init-db.sql
     volumes:
       - ./web/src/Database/init-db.sql:/init-db.sql
       - ./database/persistent_db:/var/lib/mysql
     container_name: hw2-db



volumes:
  database:
